services:
  nginx:
    image: nginx:latest
    container_name: nginx_php
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html:rw
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php_fpm
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
    entrypoint: ["/bin/sh", "-c", "mkdir -p /var/www/html/uploads && exec docker-php-entrypoint php-fpm"]

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gemasas
      MYSQL_USER: gema
      MYSQL_PASSWORD: gema123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local


