services:
  nginx:
    image: nginx:latest
    container_name: nginx_php
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html:rw
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php_fpm
    volumes:
      - ./html:/var/www/html
